#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-hdrcde
Version  : 3.4
Release  : 43
URL      : https://cran.r-project.org/src/contrib/hdrcde_3.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/hdrcde_3.4.tar.gz
Summary  : Highest Density Regions and Conditional Density Estimation
Group    : Development/Tools
License  : GPL-3.0
Requires: R-hdrcde-lib = %{version}-%{release}
Requires: R-RColorBrewer
Requires: R-ash
Requires: R-ggplot2
Requires: R-ks
Requires: R-locfit
BuildRequires : R-RColorBrewer
BuildRequires : R-ash
BuildRequires : R-ggplot2
BuildRequires : R-ks
BuildRequires : R-locfit
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# hdrcde: Highest Density Regions and Conditional Density Estimation
[![R-CMD-check](https://github.com/robjhyndman/hdrcde/workflows/R-CMD-check/badge.svg)](https://github.com/robjhyndman/hdrcde/actions)
[![CRAN_Status_Badge](http://www.r-pkg.org/badges/version/hdrcde)](https://cran.r-project.org/package=hdrcde)
[![Downloads](http://cranlogs.r-pkg.org/badges/hdrcde)](https://cran.r-project.org/package=hdrcde)
[![Licence](https://img.shields.io/badge/licence-GPL--3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0.en.html)

%package lib
Summary: lib components for the R-hdrcde package.
Group: Libraries

%description lib
lib components for the R-hdrcde package.


%prep
%setup -q -n hdrcde
pushd ..
cp -a hdrcde buildavx2
popd
pushd ..
cp -a hdrcde buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737146937

%install
export SOURCE_DATE_EPOCH=1737146937
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/hdrcde/CITATION
/usr/lib64/R/library/hdrcde/DESCRIPTION
/usr/lib64/R/library/hdrcde/INDEX
/usr/lib64/R/library/hdrcde/Meta/Rd.rds
/usr/lib64/R/library/hdrcde/Meta/data.rds
/usr/lib64/R/library/hdrcde/Meta/features.rds
/usr/lib64/R/library/hdrcde/Meta/hsearch.rds
/usr/lib64/R/library/hdrcde/Meta/links.rds
/usr/lib64/R/library/hdrcde/Meta/nsInfo.rds
/usr/lib64/R/library/hdrcde/Meta/package.rds
/usr/lib64/R/library/hdrcde/NAMESPACE
/usr/lib64/R/library/hdrcde/NEWS.md
/usr/lib64/R/library/hdrcde/R/hdrcde
/usr/lib64/R/library/hdrcde/R/hdrcde.rdb
/usr/lib64/R/library/hdrcde/R/hdrcde.rdx
/usr/lib64/R/library/hdrcde/data/Rdata.rdb
/usr/lib64/R/library/hdrcde/data/Rdata.rds
/usr/lib64/R/library/hdrcde/data/Rdata.rdx
/usr/lib64/R/library/hdrcde/help/AnIndex
/usr/lib64/R/library/hdrcde/help/aliases.rds
/usr/lib64/R/library/hdrcde/help/hdrcde.rdb
/usr/lib64/R/library/hdrcde/help/hdrcde.rdx
/usr/lib64/R/library/hdrcde/help/paths.rds
/usr/lib64/R/library/hdrcde/html/00Index.html
/usr/lib64/R/library/hdrcde/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/hdrcde/libs/hdrcde.so
/V4/usr/lib64/R/library/hdrcde/libs/hdrcde.so
/usr/lib64/R/library/hdrcde/libs/hdrcde.so
